### ISSUE TITLE
General system appearance

### ISSUE THREAD

**Issue by kreinhardt** [abyot/sun-pmt#15]
1.	**Interface style**: Why is the user settings overriding the general setting? Did the admin set this? It doesn't seem like it's possible to "unset" the user settings so the general settings will be seen.

2.	**Removing the logos**: I’m not sure how to remove the SUN logo. I removed both logos under apps->settings->appearance but only the REACH logo disappeared. 

3.	**Adding a logo**: I cannot re-add the REACH logo under apps->settings->appearance->replace image. When trying to upload a .jpg I get this “upload Image” change but the logo doesn’t appear:
![image](https://cloud.githubusercontent.com/assets/10057077/18093398/f65a7928-6ecf-11e6-92b4-009383acd0ca.png)

I have a high-quality REACH logo we can use. You can find it [here](https://drive.google.com/a/caa.columbia.edu/file/d/0B9AJjRbFGuGtLWZIVUxDYkpXbkU/view?usp=sharing)

**Comment by abyot** [comment]
@kreinhardt use .png files

**Comment by kreinhardt** [comment]
Are there specific dimensions that I should use? See:
![image](https://cloud.githubusercontent.com/assets/10057077/18167927/7287d7f0-7053-11e6-805e-8b21cf1391b0.png)

**Comment by abyot** [comment]
It is two things - what we call flag and logo.

The flag is the one we display at the top. Instead of "dhis2", which is the default, we can have a flag. You can come up with a flag... earlier I was using SUN as a flag and REACH as logo.

![image](https://cloud.githubusercontent.com/assets/4967749/18168621/e6119820-7056-11e6-972a-cb2cdb0f8cae.png)

The flag needs to be really really small... max 256x256 px.

The other is the logo. This is the one we see at the front page. I just reduced your REACH logo by 75% and see the end result...

![image](https://cloud.githubusercontent.com/assets/4967749/18168679/3395227e-7057-11e6-8c96-bc6a802d4cc0.png)

**Comment by kreinhardt** [comment]
I reduced the REACH logo and have used in both logo spots - countries can off course customize this later, using their flag/institution logo as necessary.
