### ISSUE TITLE
Data viz and GIS questions

### ISSUE THREAD

**Issue by kreinhardt** [abyot/sun-pmt#32]
1. I'm not able to get the filters for _field implementer_ and _delivery mechanism_ to work. No data is appearing, despite the arrangement used. Can you make a couple graphs or walk me through this. 

2. For the indicators that are displayed in graphs and maps, can the numbers be displayed as % instead of just numbers?

3. When making a bar graph of districts, is it possible to group and label the district values by province? (either by making them a different color per province or having some sort of label)

**Comment by abyot** [comment]
@kreinhardt  just created one. See if this works 

http://109.237.25.74:9090/sunpmt/dhis-web-visualizer/index.html?id=o2DJqT3dn7U

**Comment by kreinhardt** [comment]
Can we use the indicator instead? So the graph would show the % of target group receiving a certain action by delivery mechanism or field implementer?

**Comment by abyot** [comment]
No, that is not supported :(

The thing with indicators is that, it is not any more a raw data. This would make all sorts of pivoting and rearrangement tricky ... for example would a given set of dimensions (that one can chose from the visualizer UI) apply to both numerators and denominators ? 

While defining your indicator, you have already picked your data dimensions - specifically the target groups. All other dimensions on your data are by default aggregated. The only dimension it is supported on indicators is those on organisation units - here you can create organisation groups and group sets. And see the performance of these groups. For example you could group disaster prone areas or poor areas... and do comparison across orgunits.

Delivery mechanism and field implementer dimensions are supported on data elements because data elements are raw.

**Comment by kreinhardt** [comment]
hi @abyot, have you been able to look into this? It's fine to use the raw data but I'm just wondering if you have thought of a solution.

**Comment by abyot** [comment]
Yes, but no easy solution :(
