### ISSUE TITLE
metadata question

### ISSUE THREAD

**Issue by kreinhardt** [abyot/sun-pmt#42]
under option set - stakeholders: the stakeholder role selected is funder

what about the catalyst?

**Comment by kreinhardt** [comment]
otherwise - I'm ready to go with a clean database!

**Comment by abyot** [comment]
ok, here is the db backup

https://drive.google.com/drive/folders/0B0fAx5QYcDhmXzlqXzlzSTdabFU

the clean db is ready, make sure to have cleared your cache since we are starting on a completely new metadata. I have also found a way to filter out those below district :)

see if everything is in place.

**Comment by abyot** [comment]
Re: what about catalysts?

Sorry, missed that part. The differentiation there is basically between the ministries and others. Not specifically between Funder, Catalyst and Responsible Ministry.

Also, what we have is two sets option sets - stakeholders (catalysts and funders) and responsible ministries (responsible ministry). The same funder list is used for catalysts.

**Comment by kreinhardt** [comment]
Hi @abyot! It looks like everything is in order. I will start building the metadata and let you know how it goes! Thank you. 

Can you share the backup to my gmail account (rose.hardt@gmail.com). I think I requested access.

**Comment by abyot** [comment]
yes, just granted you access

**Comment by kreinhardt** [comment]
Got them! Thanks!
