### ISSUE TITLE
Metadata questions

### ISSUE THREAD

**Issue by kreinhardt** [abyot/sun-pmt#43]
Hi @abyot , I have been working on the metadata and completed all the steps we talked about. So far it has been going well but I have a couple questions for you. 

1. I couldn’t set “data set type” for any of the data sets (actions or target group) - can you look at this and let me know what went wrong...
2. For target groups (data elements) what type value type should be used? I left it as number, but does it need to be positive integer?
3. For category options does organization unit need to be set? 
4. Does an organization unit need to also be selected for the actions that are data elements?

**Comment by kreinhardt** [comment]
[metadata mockup v3.pdf](https://github.com/abyot/sun-pmt/files/604016/metadata.mockup.v3.pdf)


I've updated the metadata graphic, in case that helps you see if I forgot something or did something wrong. Note that I dropped the situation indicator component for space.

**Comment by abyot** [comment]
H @kreinhardt 

**Re: setting data set type**
This is because you didn't have codes to the options under option set "data set type".

**Re: value type for target groups**
I think it needs to be number as you will be entering decimals?

**Re: organisation units for category options**
Well, you can decide.. The idea is to give you an option and decide such and such options (rather stakeholders / responsible ministry are applicable for districts A & C but not B... this is especially useful if some agencies are totally focused in poor areas hence doing nothing in rich areas or working in rural & agriculture and doing nothing in urban...

**Re: organisation units for action data elements**
not sure I get you here... is this for data sets ? or for dataelements and aggregation levels?

**Comment by kreinhardt** [comment]
**Re:Re: setting data set type**
Ok! I added codes so I was able to set the data set type for the data sets! 

**Re:Re: value type for target groups**
For the value type - we actually only need decimals for the situation indicators. All of the other numbers we are dealing with are referring to people so should be whole numbers. So the type should actually be "positive integer" for all?

**Re:Re: organisation units for category options**
Right now, I have no org unit set. But if I want to collected all my information at the district level, I would have to set all the org units for category options (target groups, delivery mechanisms, stakeholders)? There are several places (between category options, data elements, etc.) where org units can be set so I'm wondering what the difference is between them all and if I have to set all of them.

**Re:Re: organisation units for action data elements**
This is related to my confusions above. Right now, I have only set the org unit for the data set and nothing else.

**Comment by kreinhardt** [comment]
ok, so I set the org until for org unit for the category options (target groups, stakeholders and delivery mechanisms), dataset (actions, target groups) and program (actions) to district. I also set the aggregation level for the action and target group data elements to district. 

1. Is this set up correct for collecting all data at the district level?
2. Do I need to set the aggregation level of the data elements called catalyst, funder and responsible ministry?
3. (**the big question**) how do I get actions to show up in the SUM PMT module? I must be missing something...
4. In the normal data entry all the datasets are showing up. For the target group dataset - how do I get the data entry to display multiple districts at one time?

**Comment by abyot** [comment]
It seems 3 and 4 above are related. Go to Apps -> System Settings -> General -> Enable multi-organisation unit forms.

No need to set aggregation levels for catalyst, funder and responsible ministry data elements.

**Re: about value types** - ok go ahead and set whatever number type that suits your case - i.e. positive integer for those values being entered through PMT app. I will make minor adjustment so that different value types are supported. For the situation indicators - or those data elements under data set "Target groups" - setting Number as value type will be ok and the system will support it.

**Re: organisation units for category options** - yes technically you can set that. But as of now applying restriction of category options per orgunit will only work for the "Target group" data set. I haven't considered filtering of category options per organisation in the PMT app. Also, this thing works best if you have a situation of the same thing - a data set and corresponding data elements for example - are being collected in all the districts but you do not want the same list of agency to apply for each organisation unit. With the thing you mentioned - all districts collecting a the same thing and using the same list of agency - filtering category options by organisation unit doesn't make sense. This is because you already have made the restriction by assigning those only the districts for your data sets.

**Re: data element aggregation level** - yes, this thing is a little confusing. Keep this in mind - aggregation level is a place you start upward aggregation i.e. if you set aggregation level "Province" - the system will aggregate starting from "Province" all the way up to "National", meaning no district data will be added. If you set "District" - it will start from District and all the way up. This thing comes handy if you are collecting the same data element at multiple levels. In your case, for example if data is collected both at Province and District levels and you wanted to see the performance at "Province" level - i.e. without necessarily adding data coming from District, you could set "Province" as aggregation level.

However, the situation in your case is data is collected only at district level. This is a default / natural case and no need to set aggregation level. The system by default will start aggregating **from the lowest level that a data is collected** and all the way up.

**Comment by kreinhardt** [comment]
Thanks @abyot  for the information - all is clear. And setting the multi-org unit forms worked for the SUM PMT data entry so I can start entering data for that.
