### ISSUE TITLE
SUM PMT reports

### ISSUE THREAD

**Issue by kreinhardt** [abyot/sun-pmt#46]
Hi Abyot, it seems the actions are not showing up in the population coverage per stakeholder report:

![image](https://cloud.githubusercontent.com/assets/10057077/20649771/105e21f2-b4c7-11e6-8f06-6b817e1fe499.png)

The actions are appearing for the other two reports.

**Comment by abyot** [comment]
Hi @kreinhardt ,

I think we missed that part totally :(

For population coverage, we have to define indicators and indicator groups...

**Comment by kreinhardt** [comment]
I already defined all the population coverage indicators so that I can use them in the normal data viz module. Is there a link that needs to be made with for the SUN PMT reports?

**Comment by abyot** [comment]
ok, great. then we need to pull all those indicators into one indicator group.

Since DHIS2 allows to have multiple indicator groups, we do not want to process all of these groups in the PMT... only those valid to action mapping.

This then means we need to create new attribute {name: Is action, code: isAction, valueType: Yes Only}

Then assign this attribute to Indicator group. Go the indicator group containing all the population indicators and set its Is action property to true.

**Comment by kreinhardt** [comment]
Ok - I have the groups and there is already an attribute that I set up as Is action

![image](https://cloud.githubusercontent.com/assets/10057077/20651637/224c7d60-b4e9-11e6-875f-c6030283c9a9.png)

In the last version it was type Yes/No. Should I change this to Yes only?

**Comment by abyot** [comment]
both ways should work. Yes/No provides more flexibility as it allows to set to "No" as well.

**Comment by kreinhardt** [comment]
Ok - the actions are showing up now! Thank you!
