### ISSUE TITLE
Parent org unit showing up as blank

### ISSUE THREAD

**Issue by kreinhardt** [abyot/sun-pmt#69]
Hi @abyot, while @chloedenavit and I were entering new metadata, we were having problems with the metadata in the tool. After I entered the org unit with a national level and 1 sub-national level, the national level showed up as blank even though I gave it a name. 

![image](https://user-images.githubusercontent.com/10057077/27591574-60308fb2-5b52-11e7-8620-77dbbf610f2f.png)

when clicking on the blank national level:
![image](https://user-images.githubusercontent.com/10057077/27591616-8131f980-5b52-11e7-85bb-36856c9d0cd3.png)

**Comment by kreinhardt** [comment]
And, when entering a dataset, the org unit is blank:
![image](https://user-images.githubusercontent.com/10057077/27591703-c6456fde-5b52-11e7-8e95-0a99a3991fed.png)

**Comment by chloedenavit** [comment]
![image](https://user-images.githubusercontent.com/21313941/27592049-ca9e5e8c-5b53-11e7-9ff9-b8aceb302019.png)

**Comment by chloedenavit** [comment]
Hi @abyot, 
Did you get a chance to look into this org unit issue?

**Comment by abyot** [comment]
Hi @chloedenavit ,

Yes, looking into it... currently the system is in version 2.25 and trying to upgrade to 2.26. That way you will get an improved system.

**Comment by chloedenavit** [comment]
Great, thanks!

**Comment by abyot** [comment]
Have looked into this in more detail, I am holding the upgrading a bit :(

A solution for now is to assign the user (in this case the admin), the root orgunit. It should be working now.

**Comment by chloedenavit** [comment]
Hi @abyot,
The parent orgunit is not blank anymore, so that is fixed. Thank you.

However, in the data entry module, the actions don't show up when I select a level to enter data:

![image](https://user-images.githubusercontent.com/21313941/27819830-4ad065e4-609c-11e7-8273-7d068c97a50c.png)

Do I need to complete another step?

**Comment by abyot** [comment]
Have you created the actions / data sets and assigned them to the unit you are planning to enter data?

**Comment by abyot** [comment]
There is a serious of metadata creation steps that you need to follow. Kris, I think, have a manual for that.

**Comment by chloedenavit** [comment]
Yes, Kris and I followed all these steps together last week. I will double check everything and then come back to you this afternoon if it's still not working.

**Comment by chloedenavit** [comment]
I realized that one of the things that Kris and I were unable to do during our creation of the metadata was  was to save new data sets. I thought it was due to the blank org unit, but it is still not working. When I try to create a new data set, it freezes on "saving" and does not ever save. 

Here is a screenshot of the Console: 

![image](https://user-images.githubusercontent.com/21313941/27824521-12d49b9a-60ad-11e7-8487-d5dda51386bc.png)

**Comment by abyot** [comment]
Should be fine now.

**Comment by chloedenavit** [comment]
Yes, it works now thanks. Is there any step I needed to complete in order for this to work?

**Comment by abyot** [comment]
not really, an issue from the system's side and that is fixed now.
