### ISSUE TITLE
Clarify the "code" requirements for shapefiles and org units

### ISSUE THREAD

**Issue by chloedenavit** [abyot/sun-pmt#74]
This was not clear in our guidance. Can you confirm that we should open the shapefiles to edit the codes, and the create GMT files to upload into the tool?

**Comment by abyot** [comment]
First the shapefile needs to be converted to GML. There are multiple tools / approaches. DHIS2 documentation explains one.

Here is what you can do to import GML into DHIS2.

1. Open the following link (this is from Zimbabwe server) 
http://154.120.241.124:8080/dhis/api/organisationUnits.json?paging=false&fields=displayName,featureType,coordinates

It lists all orgunits together with their feature type and corresponding coordinate.

2. Look into this https://docs.dhis2.org/master/en/user/html/dhis2_user_manual_en_full.html#gis_creating_setup
Since you already have GML, you can start from Step 3.

Open the GML file in Notepad++. It is important that you use Notepad++ - as it won't add unnecessary line feed and related characters.

3. Use search and replace

Replace ogr:DIST_NAME_ with ogr:Name
Save.

4. Go to Apps -> Import/Export -> GML Import
Import the GML file you just saved.

The system will display how many imported, how many ignored depending on the match you have between your orgunits's name and the name you have in the GML file.

5. You can also go and open the link from step 1 and compare the result. 
http://154.120.241.124:8080/dhis/api/organisationUnits.json?paging=false&fields=displayName,featureType,coordinates
