### ISSUE TITLE
Adjust Data entry tab (denominators) for all district in a province/region to show at once

### ISSUE THREAD

**Issue by margaret822** [abyot/sun-pmt#78]
Am thinking for a country that will work at district level and happens to have many districts or actions, the way we have organised the data entry section can be tiring as it requires opening each district for each action or SI. BUT if all districts for a regions open we could enter data for all the districts at once. Also entry for this data rely on one/or two people to enter as it is usually available at central level.  See below scree shot
[data entry view.docx](https://github.com/abyot/sun-pmt/files/1501243/data.entry.view.docx)

**Comment by chloedenavit** [comment]
Hi @abyot,

Margaret and I just compared her Data Entry (denominator) screen with the SUN PMT demo, and we realized they are very different. In the demo, the Data Set says Target Groups. In the Zimbabwe version, the Data Set says each target group name individually.

That is why hers is so tedious to fill out!  See screen shots here:

DEMO: 
![image](https://user-images.githubusercontent.com/21313941/33216616-d0f0c4f8-d134-11e7-962c-c87b0f045f70.png)


ZIMBABWE:
![image](https://user-images.githubusercontent.com/21313941/33216685-322f016c-d135-11e7-8a35-a7fc7f7f5b24.png)

**Comment by abyot** [comment]
Hi,

This is because you had each target group data element in own data set. What you can do is put all target group data elements into one target group data sets. Then you will get all appearing in one data entry screen.

To display the target data entry for all districts of a province, I have made a small fix. This means then the system needs to be updated.
